In [ ]:
#Bài 1: List, Tuple, Dict, Set Operations

my_list = [1, 2, 3, 2, 5, 1, 7, 9, 9, 4]
print(f"List ban đầu: {my_list}")

even_positions = my_list[::2]  
print(f"Các vị trí chẵn: {even_positions}")

my_tuple = tuple(my_list)
print(f"Tuple: {my_tuple}")

position_dict = {i: value for i, value in enumerate(my_list)}
print(f"Dict: {position_dict}")

my_set = set(my_list)
num_duplicates = len(my_list) - len(my_set)
print(f"Set: {my_set}")
print(f"Số phần tử bị loại trùng: {num_duplicates}")

In [ ]:
#Bài 2: File Handling and JSON Operations

import json

with open('data.txt', 'w', encoding='utf-8') as f:
    lines = [
        "Dòng 1: Đây là dòng đầu tiên",
        "Dòng 2: Thông tin sinh viên", 
        "Dòng 3: Điểm số các môn học",
        "Dòng 4: Hoạt động ngoại khóa",
        "Dòng 5: Kết quả cuối kỳ"
    ]
    for line in lines:
        f.write(line + '\n')

print("Đã tạo file data.txt")

with open('data.txt', 'r', encoding='utf-8') as f:
    for i, line in enumerate(f, 1):
        print(f"Dòng {i}: {line.strip()}")

print()

student_info = {
    "name": "An",
    "age": 20,
    "scores": [8, 9, 7]
}

print(f"Thông tin sinh viên: {student_info}")

with open('student.json', 'w', encoding='utf-8') as f:
    json.dump(student_info, f, ensure_ascii=False, indent=2)

print("Đã ghi vào student.json")

with open('student.json', 'r', encoding='utf-8') as f:
    loaded_data = json.load(f)
    print(f"JSON đọc từ file: {loaded_data}")

In [11]:
#Bài 3: NumPy Array Operations

import numpy as np

arr = np.arange(12).reshape(3, 4)
print("Mảng 3x4:")
print(arr)
print()

row_2 = arr[1, :]
print(f"Hàng 2: {row_2}")

col_3 = arr[:, 2]
print(f"Cột 3: {col_3}")

submatrix = arr[1:3, 2:4]
print(f"Submatrix: {submatrix}")

arr_float = arr.astype(np.float64)
print(f"Dtype mới: {arr_float.dtype}")
print("Mảng với dtype float64:")
print(arr_float)

Mảng 3x4:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Hàng 2: [4 5 6 7]
Cột 3: [ 2  6 10]
Submatrix: [[ 6  7]
 [10 11]]
Dtype mới: float64
Mảng với dtype float64:
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [ ]:
#Bài 4: Pandas Series and DataFrame Operations

import pandas as pd

name = ['An', 'Bình', 'Châu', 'Dũng', 'Hà']
age = [20, 21, 22, 20, 23]
score = [7.5, 8.0, 6.5, 9.0, 8.5]

score_series = pd.Series(score, index=name, name='Điểm')
print("Series điểm:")
print(score_series)
print()

df = pd.DataFrame({
    'name': name,
    'age': age,
    'score': score
})

print("DataFrame:")
print(df)
print()

print("df.info():")
df.info()
print()

print("df.describe():")
print(df.describe())
print()

high_score_students = df[df['score'] >= 8]
print("Sinh viên >= 8 điểm:")
print(high_score_students)
print()
print("Danh sách [name, age, score]:")
for _, row in high_score_students.iterrows():
    print([row['name'], row['age'], row['score']])

In [ ]:
#Bài 5: CSV File Operations and Data Analysis

import pandas as pd

students_data = {
    'id': [1, 2, 3],
    'name': ['An', 'Binh', 'Chau']
}
df_students = pd.DataFrame(students_data)
df_students.to_csv('students.csv', index=False)
print("Đã tạo students.csv:")
print(df_students)
print()

scores_data = {
    'id': [1, 1, 1, 2, 2, 2, 3, 3, 3],
    'score': [8, 7, 9, 9, 8, 10, 7, 6, 8]
}
df_scores = pd.DataFrame(scores_data)
df_scores.to_csv('scores.csv', index=False)
print("Đã tạo scores.csv:")
print(df_scores)
print()

df_students_read = pd.read_csv('students.csv')
df_scores_read = pd.read_csv('scores.csv')

print("Đọc students.csv:")
print(df_students_read)
print()
print("Đọc scores.csv:")
print(df_scores_read)
print()

df_merged = pd.merge(df_students_read, df_scores_read, on='id')
print("Merged DataFrame:")
print(df_merged)
print()

report = df_merged.groupby(['id', 'name'])['score'].agg(['min', 'max', 'mean']).reset_index()
report.columns = ['id', 'name', 'score_min', 'score_max', 'score_mean']

print("Report:")
print(report)

report.to_csv('report.csv', index=False)
print("\nĐã lưu kết quả vào report.csv")

Đã tạo students.csv:
   id  name
0   1    An
1   2  Binh
2   3  Chau

Đã tạo scores.csv:
   id  score
0   1      8
1   1      7
2   1      9
3   2      9
4   2      8
5   2     10
6   3      7
7   3      6
8   3      8

Đọc students.csv:
   id  name
0   1    An
1   2  Binh
2   3  Chau

Đọc scores.csv:
   id  score
0   1      8
1   1      7
2   1      9
3   2      9
4   2      8
5   2     10
6   3      7
7   3      6
8   3      8

Merged DataFrame:
   id  name  score
0   1    An      8
1   1    An      7
2   1    An      9
3   2  Binh      9
4   2  Binh      8
5   2  Binh     10
6   3  Chau      7
7   3  Chau      6
8   3  Chau      8

Report:
   id  name  score_min  score_max  score_mean
0   1    An          7          9         8.0
1   2  Binh          8         10         9.0
2   3  Chau          6          8         7.0

Đã lưu kết quả vào report.csv


In [ ]:
#Bài 6: NumPy Broadcasting and Mathematical Operations

import numpy as np

a = np.array([[1], [2], [3], [4]])
print(f"Mảng a shape {a.shape}:")
print(a)
print()

b = np.array([[10, 20, 30, 40, 50]])
print(f"Mảng b shape {b.shape}:")
print(b)
print()

result = a * b
print("Kết quả a * b (broadcasting):")
print(result)
print()

sqrt_result = np.sqrt(result)
print("Kết quả sqrt():")
print(sqrt_result)
print()

log_result = np.log(result)
print("Kết quả log():")
print(log_result)
print()

print("Thống kê theo axis=1 (hàng):")
print(f"Min theo hàng: {np.min(result, axis=1)}")
print(f"Max theo hàng: {np.max(result, axis=1)}")
print(f"Mean theo hàng: {np.mean(result, axis=1)}")
print(f"Std theo hàng: {np.std(result, axis=1)}")

In [ ]:
#Bài 7: Data Cleaning and Preprocessing Pipeline

import pandas as pd
import numpy as np

data = {
    'name': ['An', 'Bình', 'Châu', 'Dũng'],
    'age': [20, np.nan, 22, 21],
    'score': [8.5, np.nan, 7.0, 9.0],
    'city': ['Hà Nội', 'HCM', np.nan, 'Hà Nội']
}

df = pd.DataFrame(data)
print("Dataset ban đầu:")
print(df)
print()

print("Dữ liệu thiếu (isna()):")
print(df.isna())
print()
print("Tổng số giá trị thiếu:")
print(df.isna().sum())
print()

age_mean = df['age'].mean()
df['age'].fillna(age_mean, inplace=True)
print(f"Age cleaned (mean = {age_mean}):")
print(df['age'])
print()

score_median = df['score'].median()
df['score'].fillna(score_median, inplace=True)
print(f"Score cleaned (median = {score_median}):")
print(df['score'])
print()

df['city'].fillna('Unknown', inplace=True)
print("City cleaned:")
print(df['city'])
print()

df['city'] = df['city'].astype('category')
print(f"City (category): {df['city'].dtype}")
print(df['city'])
print()

def categorize_score(score):
    if score >= 8.5:
        return 'Good'
    elif score >= 7.0:
        return 'Average'
    else:
        return 'Bad'

df['score_level'] = df['score'].apply(categorize_score)
print("Score level:")
print(df['score_level'])
print()

age_mean_norm = df['age'].mean()
age_std_norm = df['age'].std()
df['age_normalized'] = (df['age'] - age_mean_norm) / age_std_norm
print("Age normalized:")
print(df['age_normalized'])
print()

print("DataFrame cuối cùng:")
print(df)

In [ ]:
#Bài 8: Log File Processing with Pathlib and DateTime

import pandas as pd
import json
from pathlib import Path
from datetime import datetime
import os

logs_dir = Path('logs')
logs_dir.mkdir(exist_ok=True)

log_files = {
    'log_2025-01-01.json': [
        {"user": "A", "action": "login", "duration": 5},
        {"user": "B", "action": "view", "duration": 3},
        {"user": "A", "action": "logout", "duration": 1}
    ],
    'log_2025-01-02.json': [
        {"user": "B", "action": "login", "duration": 4},
        {"user": "C", "action": "search", "duration": 7},
        {"user": "B", "action": "logout", "duration": 2}
    ],
    'log_2025-01-03.json': [
        {"user": "C", "action": "login", "duration": 3},
        {"user": "A", "action": "upload", "duration": 10},
        {"user": "C", "action": "logout", "duration": 1}
    ]
}

for filename, data in log_files.items():
    with open(logs_dir / filename, 'w') as f:
        json.dump(data, f, indent=2)

print("Đã tạo các file log:")
for file in logs_dir.glob('*.json'):
    print(f"  {file.name}")
print()

json_files = list(logs_dir.glob('*.json'))
print(f"Tìm thấy {len(json_files)} file JSON")

all_logs = []

for file_path in json_files:
    filename = file_path.stem  
    date_str = filename.replace('log_', '') 
    
    try:
        log_date = datetime.strptime(date_str, '%Y-%m-%d')
        
        with open(file_path, 'r') as f:
            logs = json.load(f)
        
        for log_entry in logs:
            log_entry['date'] = log_date.strftime('%Y-%m-%d')
            all_logs.append(log_entry)
            
        print(f"Đã xử lý {file_path.name}: {len(logs)} entries")
        
    except ValueError as e:
        print(f"Lỗi parse ngày từ {file_path.name}: {e}")

print()

df_logs = pd.DataFrame(all_logs)
print("DataFrame từ tất cả logs:")
print(df_logs)
print()

daily_summary = df_logs.groupby('date')['duration'].sum().reset_index()
daily_summary.columns = ['date', 'total_duration']

print("Tổng duration theo ngày:")
print(daily_summary)
print()

daily_summary.to_csv('daily_report.csv', index=False)
print("Đã xuất kết quả vào daily_report.csv")

print("\nNội dung daily_report.csv:")
print(pd.read_csv('daily_report.csv'))